version: "3.3"
services:
   # Notre conteneur pour notre app : Rheax
  front:
    # On définit l'image qui va servir a buid l'application monapp : ici rheax
    # Il est donc important de bien build l'image de notre application avant d'executer compose
    image: zewcro/twittair_front:latest
    restart: always
    # Dépendances de l'application , en l'occurence MYSQL
    depends_on:
      - back
    links:
      - back
    # Les ports de notre applications rheax , ici 80:80
    ports: 
      - "3000:3000"
    # On créer un réseau privé qui correspond à un environnement virtuel pour notre application
    networks:
      - monreseau
    # Notre conteneur MongoDB
  database:
    image: mongo:latest
    container_name: mongodatabase_1
    environment:
      - MONGO_INITDB_DATABASE=twittair
      - MONGO_INITDB_ROOT_USERNAME=MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:    
      - ./backend/mongodb/db_initialization.js:/docker-entrypoint-initdb.d/db_initialization.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 37017:27017
    # Notre premier microservice flask
  back: 
    #  Image de base 
    image: zewcro/twittair_back_posts_management 
    restart: always
    # Toutes les variables d'environnements pour MYSQL ( user, pass, db )
    volumes:
      - ./db/intranetgmp.sql:/docker-entrypoint-initdb.d/intranetgmp.sql
    networks:
      - monreseau
networks:
  monreseau: